---

##### PROJECT NAME AND LOCATION
# project
EE_ID :  strange-bird-356322
PathProject : .\Projects
Project : Torrey_Pines_test

#transects path (transects in EPSG:4326)
PathTransect :
    - ./DataExample
    - valid_TorreyPines.p


##### USER-DEFINED INPUTS
# Features to detect
Waterline : True
SandBar : False
Vegetation : False

# Download also RGB images (for qualitative validation)
RGB : True

#ROIs
SizeROI : 0.05   #approximate ROIs size (in degrees 1° ~ 100km)
SaveShpROI : True

# starting and ending dates (YYYY/MM/DD)
Dates:
    - 2022/04/15
    - 2022/09/01

# satellite missions wanted
Missions:
    - L8
    - L9

# projection of the output images
CRS : 'EPSG:3857'

#Clouds
MaxCloudCover : 20
CloudMasks : False

# WATERLINE INDEX band combination used : SCoWI, NDWI, AWEI, MNDWI, etc...
WaterlineIndex: SCoWI

# SANDBAR INDEX band combination used : SBI
SandBarIndex : SBI

# VEGETATION INDEX band combination used : NDVI
VegetationIndex : NDVI



##### METHODOLOGY
# preprocessing : Pansharpening, CloudMasking_Landsat, CloudMasking_Sentinel2
Preprocessing:
    - Pansharpening
    - Bicubic

# contouring method used : OtsuMS, CannyFilter
Contouring : OtsuMS

# outlier correction : IQR, modes (or None)
IQR : True
modes : True

# post processing
TidePrediction : False
PathTideData : C:\Users\Marca\Desktop\THESE\data\validation\all_sites\TORREYPINES\TORREYPINES_tides.csv
TideCorrection : True
SlopeCalculation : True
userDefinedSlope : 0
MSLOffset : 0 #If dealing with in-situ data, Offset between the datum used for the beach elevation profiles and MSL




##### OPTIONAL FOR PLOTING
# SAVING and PLOTS
Ploting : False #Be carefull if lauching on a large number of images
SpecifyTransects : True
NameTransects : ['1097']
SaveFig : True
SaveDate :
    - shpLines : False
    - shpTransects : True #Transects with cross-shore shoreline position timeseries in a json format
    - pickle : True #Python data, in a pd.Series format
...
